  sum_v3:  sum_v3.o  soma.o  soma_octal.o  ciclo_for.o  ciclo_while.o  ciclo_do_while.o
  gcc -o sum_v3  sum_v3.o  soma.o  soma_octal.o  ciclo_for.o  ciclo_while.o  ciclo_do_while.o
  sum_v3.o:  sum_v3.c  soma.h  soma_octal.h  ciclo_for.h  ciclo_while.h  ciclo_do_while.h 
  gcc -c sum_v3.c 
  soma.o:  soma.c   
  gcc -c soma.c
  soma_octal: soma_octal.c
  gcc -c soma_octal.c
  ciclo_for: ciclo_for.c   
  gcc -c ciclo_for.c
  ciclo_while: ciclo_while.c
  gcc -c ciclo_while.c
  ciclo_do_while: ciclo_do_while.c   
  gcc -c ciclo_do_while.c
  